# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
            ],
        ),
    ]
